statefulset:
  resources:
    limits:
      memory: "10Gi"
    requests:
      memory: "8Gi"
  annotations:
    sidecar.istio.io/inject: "false" #Remove sidecar until better support for cockroach + istio is provided
conf:
  cache: "2Gi"
  max-sql-memory: "2Gi"
  max-offset: 1000ms
tls:
  enabled: true
